### PR TITLE
Cri o2

### PR DESCRIPTION
**Pull request by raffaelespazzoli**
added support for crio

### CODE REVIEW

**Comment by sabre1041** [comment]
@raffaelespazzoli can you rebase?

**Comment by raffaelespazzoli** [comment]
I did rebase, do you see conflicts?

**Comment by sabre1041** [comment]
@raffaelespazzoli notice how your history in this PR included items prior to the last merge. We are going to have an ugly history with this as you can see a merge occurred in e93283f

**Comment by sabre1041** [comment]
@raffaelespazzoli github ui was displaying commits in a weird format. After manual review 👍

**Pull request merged**
